### ISSUE TITLE
superpowers server won't start

### ISSUE THREAD

**Issue by nio101** [florentpoujol/superpowers-text-asset-plugin#1]
Hi Florent,

I tried to install your plugin but then superpowers v0.1.0 server won't start with it...
It just hangs at "server starting"...

Regards,

Nicolas.

**Comment by florentpoujol** [comment]
Hey !
Thanks for the feedback, this issue is now fixed (a whole bunch of files were missing).

Unfortunately, the .zip you can get from the release page now weight about 6Mb. :(

Please confirm this is fixed on your end, then close the isssue.
Thanks again !

**Comment by nio101** [comment]
Yes, it fixed the issue, thanks! :)
